package fr.demo.metier.validator;

public interface ValidatorConstantes {

  String CADRE_ANCIEN = "CADRE_ANCIEN";

  String CADRE_DATE_NAISSANCE = "CADRE_DATE_NAISSANCE";

  String CADRE_STATUT_ACTUEL = "CADRE_STATUT_ACTUEL";

  String CADRE_CIVILITE = "CADRE_CIVILITE";

  String CADRE_NOM = "CADRE_NOM";

  String CADRE_PRENOM = "CADRE_PRENOM";

  String CADRE_EMAIL = "CADRE_EMAIL";
  
  String CADRE_TELEPHONE = "CADRE_TELEPHONE";

  String CV_TITRE = "CV_TITRE";

  String CADRE_DIPLOME_PRINCIPAL = "CADRE_DIPLOME_PRINCIPAL";

  String CV_STATUT = "CV_STATUT";

  String CV_WORD = "CV_WORD";

  String CV_FICHIER = "CV_FICHIER";

  String ETABLISSEMENT = "ETABLISSEMENT";
  
  String INTERLOCUTEUR_ANCIEN = "INTERLOCUTEUR_ANCIEN";
  
  String ID_CADRE = "ID_CADRE";

  String OFFRE = "OFFRE";
  
  String ESTIMATION_SALAIRE_REQUEST = "ESTIMATION_SALAIRE_REQUEST";

  String HABILITATION_ANCIENNE = "HABILITATION_ANCIENNE";

  String PROFIL_ANCIEN = "PROFIL_ANCIEN";
  
  String RENDEZ_VOUS = "RENDEZ_VOUS";
  
  String SIGNALER_OFFRE = "SIGNALER_OFFRE";

  String REFERENTIEL_STATIQUE_VALIDITE = "REFERENTIEL_STATIQUE_VALIDITE";

  String PROFIL_CADRE = "PROFIL_CADRE";
}
